#! python3
import re

##Function which makes sure that the password is STRONG.
## A STRONG password has at least 8 characters, and has at least one digit.


def passcheck(text):
    if len(text)<8:
        return print('That is not a STRONG password')
    checkdigRegex = re.compile(r'\d')
    checkupperRegex = re.compile(r'[A-Z]')
    if checkdigRegex.search(text) != None and checkupperRegex.search(text) != None:
        return print('That is a STRONG password.')
    print('That is not a STRONG password')

text = input('Please enter a STRONG password: ')
passcheck(text)
