#! python3
# downloadXKCD.py - Downloads every single XKCD comic.

## This code is a bit incomplete, it will run and download the first for a bit
## but the exception clause does not match what is currently thrown by bs4
## and thust needs updated.

import requests, os, bs4

url = 'http://xkcd.com' # starting url
os.makedirs('xkcd', exist_ok=True) # store comics in ./xkcd
while not url.endswith('#'):
            # ToDo : Download the page.
            print('Downloading page %s...' % url)
            res = requests.get(url)
            res.raise_for_status()

            soup = bs4.BeautifulSoup(res.text)

            # ToDo : Find the URL of the comic image.

            comicElem = soup.select('#comic img')
            if comicElem == []:
                print('Could not find comic image.')
            else:
                try:
                    comicUrl = 'http:' + comicElem[0].get('src')

            # ToDo : Download the image.
                    print('Downloading image %s...' % (comicUrl))
                    res = requests.get(comicUrl)
                    res.raise_for_status()
                except requests.exceptions.MissingSchema:
                #skip this comic.
                    prevLink = soup.select('a[rel="prev"]')[0]
                    url = 'http://xkcd.com' + prevLink.get('href')
                    continue

            # ToDo : Save the image to ./xkcd.

            imageFile = open(os.path.join('xkcd', os.path.basename(comicUrl)), 'wb')
            for chunk in res.iter_content(100000):
                imageFile.write(chunk)
            imageFile.close()

            # ToDo : Get the Prev button's url.
            prevLink = soup.select('a[rel="prev"]')[0]
            url = 'http://xkcd.com' + prevLink.get('href')

print('Done.')
